/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/global/Button/AppButton.vue')['default']
    AppIcon: typeof import('./src/components/global/AppIcon.vue')['default']
    AppParagraph: typeof import('./src/components/global/Paragraph/AppParagraph.vue')['default']
    AppSearchBar: typeof import('./src/components/global/SearchBar/AppSearchBar.vue')['default']
    AppTitle: typeof import('./src/components/global/Title/AppTitle.vue')['default']
    AppToolTip: typeof import('./src/components/global/ToolTip/AppToolTip.vue')['default']
    IconMdiCloseCircle: typeof import('~icons/mdi/close-circle')['default']
    IconMdiCloseCircleOutline: typeof import('~icons/mdi/close-circle-outline')['default']
    IconMdiCode: typeof import('~icons/mdi/code')['default']
    IconMdiDownloadCircleOutline: typeof import('~icons/mdi/download-circle-outline')['default']
    IconMdiFileDownloadOutline: typeof import('~icons/mdi/file-download-outline')['default']
    IconMdiInfo: typeof import('~icons/mdi/info')['default']
    IconMdiInfoOutline: typeof import('~icons/mdi/info-outline')['default']
    IconMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IconMdiSearch: typeof import('~icons/mdi/search')['default']
  }
}
